#!/bin/bash

#for HSBPTBIN in matMul_baseline matMul ;
#do
 for sizet in 1 2 4 8 16 #32 #1024 #256 512 # 32 64 128 ;
 #for size in 512 #1024 2048 4096 8192 16384;
 do
  size=`expr 512 \* $sizet`
  #./${HSBPTBIN}_verify $size > /dev/null
  #if [ "$?" != "0" ] ; then
  # echo 'test failed> results differ'
  # sleep 3
  # #exit
  #fi

  #mv .testlog.$size.$iter.out .testlog.$HSBPTBIN.$size.$iter.out
  for rep in {1..30};
  do
   for bin in smc_true # smc_false 
   #for bin in cuda baseline smc_false smc_true
   do
    echo $bin.$size.$rep
    nvprof ./matMul_$bin $size > .testlog.${bin}.${size}.out 2> .perflog.lowoccup.${bin}.${sizet}.$rep
    #nvprof ./nbody_$bin -compare -openacc -numbodies=$size > .testlog.${bin}.${size}.out 2> .perflog.${bin}.${sizet}.$rep
    #mv .perflog.$size.t$rep .perflog.$HSBPTBIN.$size.t$rep
    if [ "$?" != "0" ] ; then
     echo 'running failed'
     exit
    fi
   done
  done
 done
#done

