#!/bin/bash

#for HSBPTBIN in matMul_baseline matMul ;
#do
 for sizet in 16 8 4 2 1 #1024 #256 512 # 32 64 128 ;
 #for size in 512 #1024 2048 4096 8192 16384;
 do
  size=`expr 1024 \* $sizet`
  #./${HSBPTBIN}_verify $size > /dev/null
  #if [ "$?" != "0" ] ; then
  # echo 'test failed> results differ'
  # sleep 3
  # #exit
  #fi

  #mv .testlog.$size.$iter.out .testlog.$HSBPTBIN.$size.$iter.out
  for rep in {1..30};
  do
   for bin in  smctrue #cuda nosmc smcfalse    
   do
    echo $bin.$size.$rep
    nvprof ./JAC_$bin $size $size > .testlog.${bin}.${size}.out 2> .perflog.${bin}.${sizet}.$rep
    #nvprof ./nbody_$bin -compare -openacc -numbodies=$size > .testlog.${bin}.${size}.out 2> .perflog.${bin}.${sizet}.$rep
    #mv .perflog.$size.t$rep .perflog.$HSBPTBIN.$size.t$rep
    if [ "$?" != "0" ] ; then
     echo 'running failed'
     exit
    fi
   done
  done
 done
#done
