
all:
	@echo 'refer to the Makefile of each benchmark'
clean: 
	make clean -C backprop
	make clean -C bfs
	make clean -C hotspot
	#make clean -C lavaMD
	#make clean -C lud
	make clean -C nn
	make clean -C nw
	#make clean -C particlefilter
	make clean -C pathfinder
	make clean -C srad
	@echo 'cleaned up'
