#!/bin/bash

#export INPUT="../../data/hotspot/temp_1024 ../../data/hotspot/power_1024"
export INPUT="../../data/hotspot/temp_4096 ../../data/hotspot/power_4096"


#for HSBPTBIN in smc_ghostzone_16x16 smc_ghostzone_32x32
#for HSBPTBIN in smc_ghostzone_yx
for HSBPTBIN in smc_ghostzone_xy #smc_ghostzone_yx
do
 for rep in 1 2 3;
 do
  echo $HSBPTBIN $rep
  for iter in 12 ; # 3 6 9 ;
  do
   #for size in 4 5 6 7 8 12 14 16 32 64 128 256 320 1024 2048 4096;
   for size in 16 32 64 128 256 320 1024 2048 4096;
   do
    for inner in 1 2 3;
    do
     for datatype in d f
     do
      for tbsize in 16 32
      do
        for padding in 0 1
        do
         echo $size.$size.$inner.$iter.$datatype.$tbsize.$padding
         nvprof ./${HSBPTBIN}_${tbsize}${datatype}${padding} $size $size $inner $iter $INPUT > .testlog.$size.$size.$inner.$iter.$datatype.$tbsize.$padding.out 2> .perflog.$HSBPTBIN.$size.$size.$inner.$iter.$datatype.$tbsize.$padding.out.t$rep
         #./smc_ghostzone $size $size $inner $iter $INPUT > testlog.$size.$size.$inner.$iter.out 2> $HSBPTBIN.$size.$size.$inner.$iter.out.t{$rep}
         if [ "$?" != "0" ] ; then
          echo 'running failed'
          exit
         fi
         if [ "$datatype" != "f" ] ; then
          diff ../../openacc/hotspot/testlog.$size.$size.$iter.out .testlog.$size.$size.$inner.$iter.$datatype.$tbsize.$padding.out 
         fi
         if [ "$?" != "0" ] ; then
          echo 'test failed> results differ'
          sleep 3
          #exit
         fi
         done
       done
     done
    done
   done
  done
 done
done
