#!/bin/bash



# we verify smc results against baseline OpenACC.
# lets run the OpenACC version first to get the log files
echo '=========================='
echo 'compiling baseline openacc'
cd ../../openacc/hotspot/
make cuda cpu
echo '=========================='
echo 'running baseline openacc (there should not be any failure prompt!)'
bash testbench
cd ../../smc/hotspot/

echo '=========================='
echo 'compiling smc'
make cuda
echo '=========================='
echo 'comparing smc against openacc (there should not be any failure prompt!)'
export INPUT="../../data/hotspot/temp_1024 ../../data/hotspot/power_1024"
#export INPUT="../../data/hotspot/temp_4096 ../../data/hotspot/power_4096"
#for HSBPTBIN in smc_ghostzone_32x32 #smc_ghostzone_16x16
for HSBPTBIN in smc_ghostzone
#for HSBPTBIN in smc_ghostzone_xy smc_ghostzone_yx
do
# for rep in {1..30};
# do
  echo $HSBPTBIN $rep
  for iter in 12 ; # 3 6 9 ;
  do
   #for size in 4 5 6 7 8 12 14 16 32 64 128 256 320 1024 2048 4096;
   for size in 16 32 64 128 256 512 1024 #2048 4096;
   do
    for inner in 1 2 3;
    do
     echo $size.$size.$inner.$iter
     #echo  nvprof ./${HSBPTBIN} $size $size $inner $iter $INPUT
     nvprof ./${HSBPTBIN} $size $size $inner $iter $INPUT > .testlog.smc.$size.$size.$inner.$iter.out 2> .perflog2.cta32x32.$HSBPTBIN.$size.$size.$inner.$iter.out.t$rep
     #nvprof ./${HSBPTBIN} $size $size $inner $iter $INPUT > .testlog.$size.$size.$inner.$iter.out 2> .perflog2.cta16x16.$HSBPTBIN.$size.$size.$inner.$iter.out.t$rep
     #./smc_ghostzone $size $size $inner $iter $INPUT > testlog.$size.$size.$inner.$iter.out 2> $HSBPTBIN.$size.$size.$inner.$iter.out.t{$rep}
     if [ "$?" != "0" ] ; then
      echo 'running failed'
      exit
     fi
     diff ../../openacc/hotspot/.testlog.cuda.$size.$size.$iter.out .testlog.smc.$size.$size.$inner.$iter.out 
     if [ "$?" != "0" ] ; then
      echo 'test failed> results differ'
      sleep 3
      #exit
     fi
    done
   done
  done
 #done
done
