#!/bin/bash

export INPUT="../../data/hotspot/temp_4096 ../../data/hotspot/power_4096"

for rep in {1..30};
do
 echo $rep
 for iter in 12; #3 6 9 ;
 do
  for inner in 1 2 3 ;
  do
   #for size in 4 5 6 7 8 12 14 16 32 64 128 256 320 1024 2048 4096;
   for size in 16 32 64 128 256 512 1024 2048 4096;
   do
    echo $size.$iter.$inner
    nvprof ./hotspot $size $inner $iter $INPUT .testlog.$size.$size.$iter.$inner.out > /dev/null 2> .perflog.32x32.$size.$size.$iter.$inner.out.t$rep
    #./hotspot_ipmacc_cuda $size $size $iter $INPUT > testlog.$size.$size.$iter.out
    #diff testlog.$size.$size.$iter.out testlog.$size.$size.$iter.out.new
   done
  done
 done
done

